// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class РезультатПредставленияСведений {
        
        private РезультатПредставленияСведенийБКИ бКИField;
        
        private РезультатПредставленияСведенийРезультат[] результатField;
        
        private string версияField;
        
        private string идентификаторЗапросаField;
        
        private System.DateTime датаЗапросаField;
        
        private string идентификаторОтветаField;
        
        private string оГРНField;
        
        public РезультатПредставленияСведений() {
            this.версияField = "3.0";
        }
        
        /// <remarks/>
        public РезультатПредставленияСведенийБКИ БКИ {
            get {
                return this.бКИField;
            }
            set {
                this.бКИField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Результат")]
        public РезультатПредставленияСведенийРезультат[] Результат {
            get {
                return this.результатField;
            }
            set {
                this.результатField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Версия {
            get {
                return this.версияField;
            }
            set {
                this.версияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдентификаторЗапроса {
            get {
                return this.идентификаторЗапросаField;
            }
            set {
                this.идентификаторЗапросаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ДатаЗапроса {
            get {
                return this.датаЗапросаField;
            }
            set {
                this.датаЗапросаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдентификаторОтвета {
            get {
                return this.идентификаторОтветаField;
            }
            set {
                this.идентификаторОтветаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОГРН {
            get {
                return this.оГРНField;
            }
            set {
                this.оГРНField = value;
            }
        }
    }
}
