// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        ОбязательствНет,
        
        /// <remarks/>
        Обязательства,
        
        /// <remarks/>
        Ошибка,
        
        /// <remarks/>
        СведенийДляПредупрежденияНет,
        
        /// <remarks/>
        СведенийОЗапретеНет,
        
        /// <remarks/>
        СведенияДляПредупреждения,
        
        /// <remarks/>
        СведенияДляПредупрежденияНеПредоставляются,
        
        /// <remarks/>
        СведенияОЗапретеНеПредоставляются,
        
        /// <remarks/>
        СубъектНеНайден,
        
        /// <remarks/>
        УсловияЗапрета,
    }
}
