// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТипДоговор {
        
        private ТипСреднемесячныйПлатеж среднемесячныйПлатежField;
        
        private string пСКField;
        
        private System.DateTime датаПрекращенияField;
        
        private bool датаПрекращенияFieldSpecified;
        
        private string уИДField;
        
        private System.DateTime представленоField;
        
        /// <remarks/>
        public ТипСреднемесячныйПлатеж СреднемесячныйПлатеж {
            get {
                return this.среднемесячныйПлатежField;
            }
            set {
                this.среднемесячныйПлатежField = value;
            }
        }
        
        /// <remarks/>
        public string ПСК {
            get {
                return this.пСКField;
            }
            set {
                this.пСКField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ДатаПрекращения {
            get {
                return this.датаПрекращенияField;
            }
            set {
                this.датаПрекращенияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ДатаПрекращенияSpecified {
            get {
                return this.датаПрекращенияFieldSpecified;
            }
            set {
                this.датаПрекращенияFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string УИД {
            get {
                return this.уИДField;
            }
            set {
                this.уИДField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime Представлено {
            get {
                return this.представленоField;
            }
            set {
                this.представленоField = value;
            }
        }
    }
}
