// <auto-generated />
using System;
using System.Linq;
using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    public partial class ТипИННФЛсПризнаком
    {
        public bool Проверен => ПризнакПроверки == ТипИННФЛсПризнакомПризнакПроверки.Item1;

        public string НормализованноеЗначение => new string((Value ?? string.Empty).Where(char.IsDigit).ToArray());

        public void Установить(string инн, bool проверен)
        {
            if (string.IsNullOrWhiteSpace(инн))
            {
                throw new ArgumentException("ИНН не должен быть пустым.", nameof(инн));
            }

            Value = new string(инн.Where(char.IsDigit).ToArray());
            ПризнакПроверки = проверен
                ? ТипИННФЛсПризнакомПризнакПроверки.Item1
                : ТипИННФЛсПризнакомПризнакПроверки.Item0;
        }
    }
}
