// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТипЦель {
        
        private ТипЦельКодЦели кодЦелиField;
        
        private string описаниеField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ТипЦельКодЦели КодЦели {
            get {
                return this.кодЦелиField;
            }
            set {
                this.кодЦелиField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Описание {
            get {
                return this.описаниеField;
            }
            set {
                this.описаниеField = value;
            }
        }
    }
}
