// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТипСубъектТитул {
        
        private ТипФИО[] фИОField;
        
        private System.DateTime датаРожденияField;
        
        private ТипДУЛ[] документЛичностиField;
        
        private ТипИННФЛсПризнаком иННField;
        
        private string инНомерField;
        
        private string сНИЛСField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ФИО")]
        public ТипФИО[] ФИО {
            get {
                return this.фИОField;
            }
            set {
                this.фИОField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ДатаРождения {
            get {
                return this.датаРожденияField;
            }
            set {
                this.датаРожденияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ДокументЛичности")]
        public ТипДУЛ[] ДокументЛичности {
            get {
                return this.документЛичностиField;
            }
            set {
                this.документЛичностиField = value;
            }
        }
        
        /// <remarks/>
        public ТипИННФЛсПризнаком ИНН {
            get {
                return this.иННField;
            }
            set {
                this.иННField = value;
            }
        }
        
        /// <remarks/>
        public string ИнНомер {
            get {
                return this.инНомерField;
            }
            set {
                this.инНомерField = value;
            }
        }
        
        /// <remarks/>
        public string СНИЛС {
            get {
                return this.сНИЛСField;
            }
            set {
                this.сНИЛСField = value;
            }
        }
    }
}
