// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТипОбращениеОбязательство {
        
        private СправочникВидыИсточников кодИсточникаField;
        
        private ushort стадияРассмотренияField;
        
        private System.DateTime датаСтадииField;
        
        private ТипСумма суммаЗаймаField;
        
        private ushort[] причинаОтказаField;
        
        private string уИДField;
        
        /// <remarks/>
        public СправочникВидыИсточников КодИсточника {
            get {
                return this.кодИсточникаField;
            }
            set {
                this.кодИсточникаField = value;
            }
        }
        
        /// <remarks/>
        public ushort СтадияРассмотрения {
            get {
                return this.стадияРассмотренияField;
            }
            set {
                this.стадияРассмотренияField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ДатаСтадии {
            get {
                return this.датаСтадииField;
            }
            set {
                this.датаСтадииField = value;
            }
        }
        
        /// <remarks/>
        public ТипСумма СуммаЗайма {
            get {
                return this.суммаЗаймаField;
            }
            set {
                this.суммаЗаймаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ПричинаОтказа")]
        public ushort[] ПричинаОтказа {
            get {
                return this.причинаОтказаField;
            }
            set {
                this.причинаОтказаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string УИД {
            get {
                return this.уИДField;
            }
            set {
                this.уИДField = value;
            }
        }
    }
}
