// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТипУсловиеЗапрета {
        
        private System.DateTime датаЗаявленияField;
        
        private System.DateTime времяЗаявленияField;
        
        private System.DateTime началоДействияField;
        
        private СправочникУсловияЗапрета valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ДатаЗаявления {
            get {
                return this.датаЗаявленияField;
            }
            set {
                this.датаЗаявленияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
        public System.DateTime ВремяЗаявления {
            get {
                return this.времяЗаявленияField;
            }
            set {
                this.времяЗаявленияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime НачалоДействия {
            get {
                return this.началоДействияField;
            }
            set {
                this.началоДействияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public СправочникУсловияЗапрета Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
