// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТипИностранныйПредприниматель {
        
        private string номерНПField;
        
        private string регНомерField;
        
        private ТипФИО фИОField;
        
        private ТипДУЛПредпринимателя документЛичностиField;
        
        private System.DateTime датаРожденияField;
        
        /// <remarks/>
        public string НомерНП {
            get {
                return this.номерНПField;
            }
            set {
                this.номерНПField = value;
            }
        }
        
        /// <remarks/>
        public string РегНомер {
            get {
                return this.регНомерField;
            }
            set {
                this.регНомерField = value;
            }
        }
        
        /// <remarks/>
        public ТипФИО ФИО {
            get {
                return this.фИОField;
            }
            set {
                this.фИОField = value;
            }
        }
        
        /// <remarks/>
        public ТипДУЛПредпринимателя ДокументЛичности {
            get {
                return this.документЛичностиField;
            }
            set {
                this.документЛичностиField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ДатаРождения {
            get {
                return this.датаРожденияField;
            }
            set {
                this.датаРожденияField = value;
            }
        }
    }
}
