// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТипФИО {
        
        private string фамилияField;
        
        private string имяField;
        
        private string отчествоField;
        
        /// <remarks/>
        public string Фамилия {
            get {
                return this.фамилияField;
            }
            set {
                this.фамилияField = value;
            }
        }
        
        /// <remarks/>
        public string Имя {
            get {
                return this.имяField;
            }
            set {
                this.имяField = value;
            }
        }
        
        /// <remarks/>
        public string Отчество {
            get {
                return this.отчествоField;
            }
            set {
                this.отчествоField = value;
            }
        }
    }
}
