// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТипЮЛ {
        
        private string иННField;
        
        private string оГРНField;
        
        private string полноеНаименованиеField;
        
        private string сокращенноеНаименованиеField;
        
        private object иноеНаименованиеField;
        
        private СправочникВидыПользователя кодВидаПользователяField;
        
        private string признакРегистрацииРФField;
        
        public ТипЮЛ() {
            this.признакРегистрацииРФField = "1";
        }
        
        /// <remarks/>
        public string ИНН {
            get {
                return this.иННField;
            }
            set {
                this.иННField = value;
            }
        }
        
        /// <remarks/>
        public string ОГРН {
            get {
                return this.оГРНField;
            }
            set {
                this.оГРНField = value;
            }
        }
        
        /// <remarks/>
        public string ПолноеНаименование {
            get {
                return this.полноеНаименованиеField;
            }
            set {
                this.полноеНаименованиеField = value;
            }
        }
        
        /// <remarks/>
        public string СокращенноеНаименование {
            get {
                return this.сокращенноеНаименованиеField;
            }
            set {
                this.сокращенноеНаименованиеField = value;
            }
        }
        
        /// <remarks/>
        public object ИноеНаименование {
            get {
                return this.иноеНаименованиеField;
            }
            set {
                this.иноеНаименованиеField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СправочникВидыПользователя КодВидаПользователя {
            get {
                return this.кодВидаПользователяField;
            }
            set {
                this.кодВидаПользователяField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ПризнакРегистрацииРФ {
            get {
                return this.признакРегистрацииРФField;
            }
            set {
                this.признакРегистрацииРФField = value;
            }
        }
    }
}
