// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТипДУЛ {
        
        private string серияField;
        
        private string номерField;
        
        private System.DateTime датаВыдачиField;
        
        private string гражданствоField;
        
        private СправочникДУЛ кодДУЛField;
        
        /// <remarks/>
        public string Серия {
            get {
                return this.серияField;
            }
            set {
                this.серияField = value;
            }
        }
        
        /// <remarks/>
        public string Номер {
            get {
                return this.номерField;
            }
            set {
                this.номерField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ДатаВыдачи {
            get {
                return this.датаВыдачиField;
            }
            set {
                this.датаВыдачиField = value;
            }
        }
        
        /// <remarks/>
        public string Гражданство {
            get {
                return this.гражданствоField;
            }
            set {
                this.гражданствоField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СправочникДУЛ КодДУЛ {
            get {
                return this.кодДУЛField;
            }
            set {
                this.кодДУЛField = value;
            }
        }
    }
}
