// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТипИЮ {
        
        private string номерНПField;
        
        private string регНомерField;
        
        private string lEIField;
        
        private string полноеНаименованиеField;
        
        private string сокращенноеНаименованиеField;
        
        private string иноеНаименованиеField;
        
        private СправочникВидыПользователя кодВидаПользователяField;
        
        private string признакРегистрацииРФField;
        
        public ТипИЮ() {
            this.признакРегистрацииРФField = "0";
        }
        
        /// <remarks/>
        public string НомерНП {
            get {
                return this.номерНПField;
            }
            set {
                this.номерНПField = value;
            }
        }
        
        /// <remarks/>
        public string РегНомер {
            get {
                return this.регНомерField;
            }
            set {
                this.регНомерField = value;
            }
        }
        
        /// <remarks/>
        public string LEI {
            get {
                return this.lEIField;
            }
            set {
                this.lEIField = value;
            }
        }
        
        /// <remarks/>
        public string ПолноеНаименование {
            get {
                return this.полноеНаименованиеField;
            }
            set {
                this.полноеНаименованиеField = value;
            }
        }
        
        /// <remarks/>
        public string СокращенноеНаименование {
            get {
                return this.сокращенноеНаименованиеField;
            }
            set {
                this.сокращенноеНаименованиеField = value;
            }
        }
        
        /// <remarks/>
        public string ИноеНаименование {
            get {
                return this.иноеНаименованиеField;
            }
            set {
                this.иноеНаименованиеField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СправочникВидыПользователя КодВидаПользователя {
            get {
                return this.кодВидаПользователяField;
            }
            set {
                this.кодВидаПользователяField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ПризнакРегистрацииРФ {
            get {
                return this.признакРегистрацииРФField;
            }
            set {
                this.признакРегистрацииРФField = value;
            }
        }
    }
}
