// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТипЮЛБазовый {
        
        private string иННField;
        
        private string оГРНField;
        
        private string полноеНаименованиеField;
        
        /// <remarks/>
        public string ИНН {
            get {
                return this.иННField;
            }
            set {
                this.иННField = value;
            }
        }
        
        /// <remarks/>
        public string ОГРН {
            get {
                return this.оГРНField;
            }
            set {
                this.оГРНField = value;
            }
        }
        
        /// <remarks/>
        public string ПолноеНаименование {
            get {
                return this.полноеНаименованиеField;
            }
            set {
                this.полноеНаименованиеField = value;
            }
        }
    }
}
