// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТипСогласие {
        
        private ТипСогласиеВыдано выданоField;
        
        private ТипЦель[] цельField;
        
        private ТипСогласиеДоговор договорField;
        
        private string хэшКодField;
        
        private System.DateTime датаВыдачиField;
        
        private СправочникСрокиСогласия срокДействияField;
        
        private СправочникОснованияПередачиСогласия основаниеПередачиField;
        
        private bool основаниеПередачиFieldSpecified;
        
        private string обОтветственностиПредупрежденField;
        
        public ТипСогласие() {
            this.обОтветственностиПредупрежденField = "1";
        }
        
        /// <remarks/>
        public ТипСогласиеВыдано Выдано {
            get {
                return this.выданоField;
            }
            set {
                this.выданоField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Цель")]
        public ТипЦель[] Цель {
            get {
                return this.цельField;
            }
            set {
                this.цельField = value;
            }
        }
        
        /// <remarks/>
        public ТипСогласиеДоговор Договор {
            get {
                return this.договорField;
            }
            set {
                this.договорField = value;
            }
        }
        
        /// <remarks/>
        public string ХэшКод {
            get {
                return this.хэшКодField;
            }
            set {
                this.хэшКодField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ДатаВыдачи {
            get {
                return this.датаВыдачиField;
            }
            set {
                this.датаВыдачиField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СправочникСрокиСогласия СрокДействия {
            get {
                return this.срокДействияField;
            }
            set {
                this.срокДействияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СправочникОснованияПередачиСогласия ОснованиеПередачи {
            get {
                return this.основаниеПередачиField;
            }
            set {
                this.основаниеПередачиField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ОснованиеПередачиSpecified {
            get {
                return this.основаниеПередачиFieldSpecified;
            }
            set {
                this.основаниеПередачиFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОбОтветственностиПредупрежден {
            get {
                return this.обОтветственностиПредупрежденField;
            }
            set {
                this.обОтветственностиПредупрежденField = value;
            }
        }
    }
}
