// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ТипИП {
        
        private string иННИПField;
        
        private string оГРНИПField;
        
        private string сНИЛСField;
        
        private ТипФИО фИОField;
        
        private ТипДУЛПредпринимателя документЛичностиField;
        
        private System.DateTime датаРожденияField;
        
        /// <remarks/>
        public string ИННИП {
            get {
                return this.иННИПField;
            }
            set {
                this.иННИПField = value;
            }
        }
        
        /// <remarks/>
        public string ОГРНИП {
            get {
                return this.оГРНИПField;
            }
            set {
                this.оГРНИПField = value;
            }
        }
        
        /// <remarks/>
        public string СНИЛС {
            get {
                return this.сНИЛСField;
            }
            set {
                this.сНИЛСField = value;
            }
        }
        
        /// <remarks/>
        public ТипФИО ФИО {
            get {
                return this.фИОField;
            }
            set {
                this.фИОField = value;
            }
        }
        
        /// <remarks/>
        public ТипДУЛПредпринимателя ДокументЛичности {
            get {
                return this.документЛичностиField;
            }
            set {
                this.документЛичностиField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ДатаРождения {
            get {
                return this.датаРожденияField;
            }
            set {
                this.датаРожденияField = value;
            }
        }
    }
}
