version: '3.8'

x-common-deploy: &common-deploy
  resources:
    limits:
      memory: 300M
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s

x-main-app: &main-app
  image: ${DOCKER_REGISTRY-}qbchdbsaversdc
  build:
    context: .
    dockerfile: qbch_db_saver_sdc/Dockerfile
  environment:
    ERROR_APP: false
    PARALLEL: 1
    DOTNET_NUGET_SIGNATURE_VERIFICATION: false
  deploy:
    <<: *common-deploy

x-error-app: &error-app
  image: ${DOCKER_REGISTRY-}qbchdbsaversdc
  build:
    context: .
    dockerfile: qbch_db_saver_sdc/Dockerfile
  environment:
    ERROR_APP: true
    PARALLEL: 1
    DOTNET_NUGET_SIGNATURE_VERIFICATION: false
  deploy:
    <<: *common-deploy

services:
  app1:
    container_name: "a1"
    <<: *main-app
  app2:
    container_name: "a2"
    <<: *main-app
  app3:
    container_name: "a3"
    <<: *main-app
  app4:
    container_name: "a4"
    <<: *main-app
  app5:
    container_name: "a5"
    <<: *main-app
  app6:
    container_name: "a6"
    <<: *main-app
  app7:
    container_name: "a7"
    <<: *main-app
  app8:
    container_name: "a8"
    <<: *main-app
  app9:
    container_name: "a9"
    <<: *main-app
  app10:
    container_name: "a10"
    <<: *main-app
  error_app:
    container_name: "e1"
    <<: *error-app
  error_app1:
    container_name: "e2"
    <<: *error-app
  error_app2:
    <<: *error-app
    container_name: "e3"
  error_app3:
    <<: *error-app
    container_name: "e4"
  error_app4:
    <<: *error-app
    container_name: "e5"
  error_app5:
    <<: *error-app
    container_name: "e6"
  error_app6:
    <<: *error-app
    container_name: "e7"
  error_app7:
    <<: *error-app
    container_name: "e8"
  error_app8:
    <<: *error-app
    container_name: "e9"
  error_app9:
    <<: *error-app
    container_name: "e10"