// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ПредставлениеСведенийСведенияДоговор {
        
        private ТипСубъектТитул субъектField;
        
        private object itemField;
        
        /// <remarks/>
        public ТипСубъектТитул Субъект {
            get {
                return this.субъектField;
            }
            set {
                this.субъектField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Добавить", typeof(ТипДоговор))]
        [System.Xml.Serialization.XmlElementAttribute("Удалить", typeof(ПредставлениеСведенийСведенияДоговорУдалить))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
}
