// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ПредставлениеСведений {
        
        private ПредставлениеСведенийБКИ бКИField;
        
        private ПредставлениеСведенийСведения[] сведенияField;
        
        private string версияField;
        
        private string идентификаторЗапросаField;
        
        private System.DateTime датаЗапросаField;
        
        public ПредставлениеСведений() {
            this.версияField = "3.0";
        }
        
        /// <remarks/>
        public ПредставлениеСведенийБКИ БКИ {
            get {
                return this.бКИField;
            }
            set {
                this.бКИField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Сведения")]
        public ПредставлениеСведенийСведения[] Сведения {
            get {
                return this.сведенияField;
            }
            set {
                this.сведенияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Версия {
            get {
                return this.версияField;
            }
            set {
                this.версияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдентификаторЗапроса {
            get {
                return this.идентификаторЗапросаField;
            }
            set {
                this.идентификаторЗапросаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ДатаЗапроса {
            get {
                return this.датаЗапросаField;
            }
            set {
                this.датаЗапросаField = value;
            }
        }
    }
}
