// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ПредставлениеСведенийСведенияОбращениеОбязательствоУдалить {
        
        private string уИДField;
        
        private ushort стадияРассмотренияField;
        
        private bool стадияРассмотренияFieldSpecified;
        
        private string причинаField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string УИД {
            get {
                return this.уИДField;
            }
            set {
                this.уИДField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort СтадияРассмотрения {
            get {
                return this.стадияРассмотренияField;
            }
            set {
                this.стадияРассмотренияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтадияРассмотренияSpecified {
            get {
                return this.стадияРассмотренияFieldSpecified;
            }
            set {
                this.стадияРассмотренияFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Причина {
            get {
                return this.причинаField;
            }
            set {
                this.причинаField = value;
            }
        }
    }
}
