// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ЗапросСведенийАбонентИностранноеЛицо {
        
        private string номерНПField;
        
        private string регНомерField;
        
        /// <remarks/>
        public string НомерНП {
            get {
                return this.номерНПField;
            }
            set {
                this.номерНПField = value;
            }
        }
        
        /// <remarks/>
        public string РегНомер {
            get {
                return this.регНомерField;
            }
            set {
                this.регНомерField = value;
            }
        }
    }
}
