// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ЗапросСведенийЗапрос {
        
        private ЗапросСведенийЗапросИсточник источникField;
        
        private ТипСубъектТитул субъектField;
        
        private ТипСогласие согласиеField;
        
        private ТипЦель[] цельField;
        
        private ЗапросСведенийЗапросСуммаОбязательства суммаОбязательстваField;
        
        private string порядковыйНомерField;
        
        /// <remarks/>
        public ЗапросСведенийЗапросИсточник Источник {
            get {
                return this.источникField;
            }
            set {
                this.источникField = value;
            }
        }
        
        /// <remarks/>
        public ТипСубъектТитул Субъект {
            get {
                return this.субъектField;
            }
            set {
                this.субъектField = value;
            }
        }
        
        /// <remarks/>
        public ТипСогласие Согласие {
            get {
                return this.согласиеField;
            }
            set {
                this.согласиеField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Цель")]
        public ТипЦель[] Цель {
            get {
                return this.цельField;
            }
            set {
                this.цельField = value;
            }
        }
        
        /// <remarks/>
        public ЗапросСведенийЗапросСуммаОбязательства СуммаОбязательства {
            get {
                return this.суммаОбязательстваField;
            }
            set {
                this.суммаОбязательстваField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string ПорядковыйНомер {
            get {
                return this.порядковыйНомерField;
            }
            set {
                this.порядковыйНомерField = value;
            }
        }
    }
}
