// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ЗапросСведенийАбонентИндивидуальныйПредприниматель {
        
        private string иННИПField;
        
        private string оГРНИПField;
        
        /// <remarks/>
        public string ИННИП {
            get {
                return this.иННИПField;
            }
            set {
                this.иННИПField = value;
            }
        }
        
        /// <remarks/>
        public string ОГРНИП {
            get {
                return this.оГРНИПField;
            }
            set {
                this.оГРНИПField = value;
            }
        }
    }
}
