// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ЗапросСведений {
        
        private ЗапросСведенийАбонент абонентField;
        
        private ЗапросСведенийЗапрос[] запросField;
        
        private string версияField;
        
        private string идентификаторЗапросаField;
        
        private System.DateTime датаЗапросаField;
        
        private СправочникСпособыЗапроса типЗапросаField;
        
        private СправочникВидыСведений кодСведенийField;
        
        private СправочникРежимыЗапроса режимЗапросаField;
        
        public ЗапросСведений() {
            this.версияField = "3.0";
        }
        
        /// <remarks/>
        public ЗапросСведенийАбонент Абонент {
            get {
                return this.абонентField;
            }
            set {
                this.абонентField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Запрос")]
        public ЗапросСведенийЗапрос[] Запрос {
            get {
                return this.запросField;
            }
            set {
                this.запросField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Версия {
            get {
                return this.версияField;
            }
            set {
                this.версияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдентификаторЗапроса {
            get {
                return this.идентификаторЗапросаField;
            }
            set {
                this.идентификаторЗапросаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime ДатаЗапроса {
            get {
                return this.датаЗапросаField;
            }
            set {
                this.датаЗапросаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СправочникСпособыЗапроса ТипЗапроса {
            get {
                return this.типЗапросаField;
            }
            set {
                this.типЗапросаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СправочникВидыСведений КодСведений {
            get {
                return this.кодСведенийField;
            }
            set {
                this.кодСведенийField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СправочникРежимыЗапроса РежимЗапроса {
            get {
                return this.режимЗапросаField;
            }
            set {
                this.режимЗапросаField = value;
            }
        }
    }
}
