// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ЗапросСведенийЗапросИсточник {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИндивидуальныйПредприниматель", typeof(ТипИП))]
        [System.Xml.Serialization.XmlElementAttribute("ИностранноеЮЛ", typeof(ЗапросСведенийЗапросИсточникИностранноеЮЛ))]
        [System.Xml.Serialization.XmlElementAttribute("ИностранныйПредприниматель", typeof(ТипИностранныйПредприниматель))]
        [System.Xml.Serialization.XmlElementAttribute("ЮридическоеЛицо", typeof(ЗапросСведенийЗапросИсточникЮридическоеЛицо))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
}
