// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ОтветНаЗапросСведенийСведения {
        
        private ТипСубъектТитул титульнаяЧастьField;
        
        private ОтветНаЗапросСведенийСведенияКБКИ[] кБКИField;
        
        private string порядковыйНомерField;
        
        /// <remarks/>
        public ТипСубъектТитул ТитульнаяЧасть {
            get {
                return this.титульнаяЧастьField;
            }
            set {
                this.титульнаяЧастьField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("КБКИ")]
        public ОтветНаЗапросСведенийСведенияКБКИ[] КБКИ {
            get {
                return this.кБКИField;
            }
            set {
                this.кБКИField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string ПорядковыйНомер {
            get {
                return this.порядковыйНомерField;
            }
            set {
                this.порядковыйНомерField = value;
            }
        }
    }
}
