// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ОтветНаЗапросСведенийСведенияКБКИСведенияДляПредупреждения {
        
        private ОтветНаЗапросСведенийСведенияКБКИСведенияДляПредупрежденияБКИ[] бКИField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("БКИ")]
        public ОтветНаЗапросСведенийСведенияКБКИСведенияДляПредупрежденияБКИ[] БКИ {
            get {
                return this.бКИField;
            }
            set {
                this.бКИField = value;
            }
        }
    }
}
