// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ОтветНаЗапросСведенийСведенияКБКИ {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private string оГРНField;
        
        private System.DateTime поСостояниюНаField;
        
        private string идентификаторОтветаField;
        
        private ОтветНаЗапросСведенийСведенияКБКИПризнакНаличияКИ признакНаличияКИField;
        
        private bool признакНаличияКИFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ОбязательствНет", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("Обязательства", typeof(ОтветНаЗапросСведенийСведенияКБКИОбязательства))]
        [System.Xml.Serialization.XmlElementAttribute("Ошибка", typeof(ТипОшибка))]
        [System.Xml.Serialization.XmlElementAttribute("СведенийДляПредупрежденияНет", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("СведенийОЗапретеНет", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("СведенияДляПредупреждения", typeof(ОтветНаЗапросСведенийСведенияКБКИСведенияДляПредупреждения))]
        [System.Xml.Serialization.XmlElementAttribute("СведенияДляПредупрежденияНеПредоставляются", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("СведенияОЗапретеНеПредоставляются", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("СубъектНеНайден", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("УсловияЗапрета", typeof(ОтветНаЗапросСведенийСведенияКБКИУсловияЗапрета))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОГРН {
            get {
                return this.оГРНField;
            }
            set {
                this.оГРНField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ПоСостояниюНа {
            get {
                return this.поСостояниюНаField;
            }
            set {
                this.поСостояниюНаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдентификаторОтвета {
            get {
                return this.идентификаторОтветаField;
            }
            set {
                this.идентификаторОтветаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ОтветНаЗапросСведенийСведенияКБКИПризнакНаличияКИ ПризнакНаличияКИ {
            get {
                return this.признакНаличияКИField;
            }
            set {
                this.признакНаличияКИField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ПризнакНаличияКИSpecified {
            get {
                return this.признакНаличияКИFieldSpecified;
            }
            set {
                this.признакНаличияКИFieldSpecified = value;
            }
        }
    }
}
