// <auto-generated />
    using System.Xml.Serialization;

namespace QBCH.Lib.qcb_xml.v3_0
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ОтветНаЗапросСведений {
        
        private ОтветНаЗапросСведенийСведения[] сведенияField;
        
        private string версияField;
        
        private string идентификаторЗапросаField;
        
        private string датаЗапросаField;
        
        private string идентификаторОтветаField;
        
        private string оГРНField;
        
        private СправочникСпособыЗапроса типОтветаField;
        
        private СправочникРежимыЗапроса режимЗапросаField;
        
        public ОтветНаЗапросСведений() {
            this.версияField = "3.0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Сведения")]
        public ОтветНаЗапросСведенийСведения[] Сведения {
            get {
                return this.сведенияField;
            }
            set {
                this.сведенияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Версия {
            get {
                return this.версияField;
            }
            set {
                this.версияField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдентификаторЗапроса {
            get {
                return this.идентификаторЗапросаField;
            }
            set {
                this.идентификаторЗапросаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаЗапроса {
            get {
                return this.датаЗапросаField;
            }
            set {
                this.датаЗапросаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдентификаторОтвета {
            get {
                return this.идентификаторОтветаField;
            }
            set {
                this.идентификаторОтветаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОГРН {
            get {
                return this.оГРНField;
            }
            set {
                this.оГРНField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СправочникСпособыЗапроса ТипОтвета {
            get {
                return this.типОтветаField;
            }
            set {
                this.типОтветаField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public СправочникРежимыЗапроса РежимЗапроса {
            get {
                return this.режимЗапросаField;
            }
            set {
                this.режимЗапросаField = value;
            }
        }
    }
}
